export const action = {
  FETCH_DATA: 'FETCH_DATA',
  LOADING: 'LOADING',
  ERROR: 'ERROR',
  TOGGLE_OPEN: 'TOGGLE_OPEN',
  ADD_DATA: 'ADD_DATA',
  DELETE_DATA: 'DELETE_DATA',
  UPDATE_DATA: 'UPDATE_DATA',
};
